using System;

namespace LuminaSharp;

/// <summary>
/// The engine-facing call surface: managed -&gt; native. Logging goes through the bootstrap exporter
/// table (a function pointer captured in the default ALC so it survives script reloads); every other
/// entry is a <c>[NativeCall] static partial</c> method whose <c>delegate* unmanaged</c> field, resolve,
/// and marshalling are generated by <c>NativeCallGenerator</c> (defaults: module "LuminaNative", entry
/// "LuminaSharp_{MethodName}"). Pure marshalling mechanics live in <see cref="Interop"/>.
/// </summary>
public static unsafe partial class Native
{
    private static FExporterTable Exports;

    internal static void SetExports(FExporterTable Table)
    {
        Exports = Table;
    }

    public static void Log(ELogLevel Level, string Message)
    {
        if (Exports.Log == null)
        {
            return;
        }

        Span<byte> Scratch = stackalloc byte[1024];
        Interop.FInteropString Encoded = new(Message, Scratch);
        try
        {
            Exports.Log((int)Level, Encoded.Pointer, Encoded.Length);
        }
        finally
        {
            Encoded.Free();
        }
    }

    // The world's own FSystemContext*, so OnTeardown gets a valid context outside a scheduler tick.
    [NativeCall(EntryPoint = "LuminaSharp_World_GetSystemContext")] public static partial IntPtr WorldGetSystemContext(ulong World);

    [NativeCall(EntryPoint = "LuminaSharp_EntityScript_MarkFaulted")] public static partial void EntityScriptMarkFaulted(IntPtr Script);


    // Row memory as a raw pointer, since the row type is only known at runtime; CDataTable gates the reads.
    [NativeCall(EntryPoint = "LuminaSharp_DataTable_FindRow")] public static partial IntPtr DataTableFindRow(IntPtr Table, string RowName);
    [NativeCall(EntryPoint = "LuminaSharp_DataTable_GetRowAt")] public static partial IntPtr DataTableGetRowAt(IntPtr Table, int Index);
    [NativeCall(EntryPoint = "LuminaSharp_DataTableHandle_GetRowMemory")] public static partial IntPtr DataTableHandleGetRowMemory(IntPtr Handle);

    // TSubclassOf. The setter is a shim rather than a byte write so the MetaClass constraint is enforced.
    [NativeCall] public static partial IntPtr PropGetClass(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetClass(IntPtr C, IntPtr Prop, IntPtr Class);
    [NativeCall] public static partial IntPtr FindClassByName(string Name);
    [NativeCall] public static partial IntPtr NewObject(IntPtr Class, IntPtr Package, string Name);

    // Reflected functions, for the dispatcher that reads a call frame through its parameters.
    [NativeCall] public static partial int FunctionParamCount(IntPtr Function);
    [NativeCall] public static partial IntPtr FunctionParamAt(IntPtr Function, int Index);
    [NativeCall] public static partial IntPtr FunctionReturnParam(IntPtr Function);
    [NativeCall] public static partial string FunctionGetName(IntPtr Function);

    // Points native dispatch at the generated invoker, and drops every such pointer before a reload.
    [NativeCall] public static partial void FunctionPublishInvoker(IntPtr Function, nint Invoker, IntPtr Offsets);
    [NativeCall] public static partial void FunctionClearInvokers();

    // The offset of a property within whatever container holds it, which is how a call frame's blittable
    // slots are addressed without a crossing per argument.
    [NativeCall] public static partial int PropertyOffset(IntPtr Prop);

    // The width of the slot at that offset, which for an enum is its underlying type's width.
    [NativeCall] public static partial int PropertySize(IntPtr Prop);
    [NativeCall] public static partial string ClassGetName(IntPtr Class);
    [NativeCall] public static partial IntPtr ClassGetDefaultObject(IntPtr Class);

    // Copies a whole struct value into the property's slot, for a reflected function returning one by value.
    [NativeCall] public static partial void PropCopyStruct(IntPtr C, IntPtr Prop, IntPtr Source);

    // TSubStructOf. The setter is a shim rather than a byte write so the MetaStruct constraint is enforced.
    [NativeCall] public static partial IntPtr PropGetSubStruct(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetSubStruct(IntPtr C, IntPtr Prop, IntPtr Struct);
    [NativeCall] public static partial IntPtr FindStructByName(string Name);
    [NativeCall] public static partial string StructGetName(IntPtr Struct);

    // Instanced structs, addressed by raw pointer so a member and a container element use the same calls.
    [NativeCall] public static partial string InstancedStructGetType(IntPtr Ptr);
    [NativeCall] public static partial IntPtr InstancedStructGetMemory(IntPtr Ptr);
    [NativeCall] public static partial int InstancedStructIsA(IntPtr Ptr, string TypeName);
    [NativeCall] public static partial void InstancedStructInitializeAs(IntPtr Ptr, string TypeName);
    [NativeCall] public static partial void InstancedStructReset(IntPtr Ptr);

    // The same path access as PropGetAssetPath, against a bare FSoftObjectPath such as a container element.
    [NativeCall] public static partial string SoftPathGet(IntPtr PathPtr);
    [NativeCall] public static partial void SoftPathSet(IntPtr PathPtr, string Path);

    // Copies one reflected struct value over another, for a container element whose type owns heap members.
    [NativeCall] public static partial void StructAssign(IntPtr Dst, IntPtr Src, string TypeName);

    // TOptional access. The get returns the payload address, or zero when the optional is unset.
    [NativeCall] public static partial IntPtr PropOptionalGetValue(IntPtr Container, IntPtr Prop);

    // The payload property, whose width the managed side copies through.
    [NativeCall] public static partial IntPtr PropOptionalInner(IntPtr Prop);
    [NativeCall] public static partial void PropOptionalSetValue(IntPtr Container, IntPtr Prop, IntPtr Value);
    [NativeCall] public static partial void PropOptionalReset(IntPtr Container, IntPtr Prop);

    [NativeCall] public static partial IntPtr OptionalValueAt(IntPtr Member, IntPtr Prop);

    [NativeCall] public static partial void OptionalSetValueAt(IntPtr Member, IntPtr Prop, IntPtr Value);

    [NativeCall] public static partial void OptionalResetAt(IntPtr Member, IntPtr Prop);

    // Component op-table access. The token returned by FindComponentOps is resolved once per type and
    // reused; the get/has/emplace/remove calls take it plus the world + entity.

    [NativeCall] public static partial IntPtr FindComponentOps(string TypeName);
    // Pure reads (try_get / any_of): non-blocking, no managed re-entry -> SuppressGCTransition.
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr GetComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall(SuppressGCTransition = true)] public static partial int HasComponent(ulong World, uint Entity, IntPtr Ops);

    // Hand-bound, because the out-pointer to the pool's layout epoch is not a shape the generator covers.
    public static IntPtr GetComponentTracked(ulong World, uint Entity, IntPtr Ops, uint** OutEpoch)
    {
        return GetComponentTracked_(World, Entity, Ops, OutEpoch);
    }

    public static bool TrackComponentPointer(IntPtr Payload, IntPtr Ops, out ulong World, out uint Entity, out uint* Epoch)
    {
        ulong OutWorld = 0;
        uint OutEntity = 0;
        uint* OutEpoch = null;
        bool bFound = TrackComponentPointer_ != null && TrackComponentPointer_(Payload, Ops, &OutWorld, &OutEntity, &OutEpoch) != 0;
        World = OutWorld;
        Entity = OutEntity;
        Epoch = OutEpoch;
        return bFound;
    }

    private static readonly delegate* unmanaged[Cdecl]<IntPtr, IntPtr, ulong*, uint*, uint**, int> TrackComponentPointer_ =
        (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, ulong*, uint*, uint**, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_TrackComponentPointer");

    private static readonly delegate* unmanaged[Cdecl, SuppressGCTransition]<ulong, uint, IntPtr, uint**, IntPtr> GetComponentTracked_ =
        (delegate* unmanaged[Cdecl, SuppressGCTransition]<ulong, uint, IntPtr, uint**, IntPtr>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_GetComponentTracked");
    // Emplace/Remove fire on_construct/on_destroy, which can re-enter managed (signal trampolines) -> not safe.
    [NativeCall] public static partial IntPtr EmplaceComponent(ulong World, uint Entity, IntPtr Ops);
    [NativeCall] public static partial int RemoveComponent(ulong World, uint Entity, IntPtr Ops);

    // Registry signals. Connect binds a managed thunk (+ GCHandle context) to a component's
    // on_construct/on_destroy/on_update sink and returns an opaque subscription handle; Disconnect releases
    // it. Patch fires on_update for an entity's component (the manual signal pulse). Kind: 0/1/2.

    [NativeCall] public static partial IntPtr RegistryConnect(ulong World, IntPtr Ops, int Kind);
    [NativeCall] public static partial IntPtr RegistryGetSignalDelegate(IntPtr Listener);
    [NativeCall] public static partial void RegistryDisconnect(ulong World, IntPtr Ops, int Kind, IntPtr Handle);
    [NativeCall] public static partial void RegistryPatch(ulong World, uint Entity, IntPtr Ops);

    // runtime view iteration for the C# View<...>. Native gathers a CHUNK of entities + parallel
    // component pointers per call (one crossing per chunk). Hand-written delegate* binds: the chunk
    // pointers (uint*, void**) aren't shapes the [NativeCall] generator covers. See DotNetView.cpp.

    public static IntPtr ViewBegin(ulong World, IntPtr* IncludeOps, int NInc, IntPtr* ExcludeOps, int NExc)
    {
        return ViewBegin_(World, IncludeOps, NInc, ExcludeOps, NExc);
    }

    public static int ViewNextChunk(IntPtr State, uint* OutEntities, IntPtr* OutPtrs, int MaxCount, int NInclude)
    {
        return ViewNextChunk_(State, OutEntities, OutPtrs, MaxCount, NInclude);
    }

    public static void ViewEnd(IntPtr State)
    {
        ViewEnd_(State);
    }

    private static readonly delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr> ViewBegin_ =
        (delegate* unmanaged[Cdecl]<ulong, IntPtr*, int, IntPtr*, int, IntPtr>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewBegin");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int> ViewNextChunk_ =
        (delegate* unmanaged[Cdecl]<IntPtr, uint*, IntPtr*, int, int, int>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewNextChunk");
    private static readonly delegate* unmanaged[Cdecl]<IntPtr, void> ViewEnd_ =
        (delegate* unmanaged[Cdecl]<IntPtr, void>)NativeBindings.Resolve(Host.NativeLibrary, "LuminaSharp_ViewEnd");

    // Asset loading. String args are UTF-8 encoded by the generated marshalling; the engine VFS resolves
    // the path. Backs the C# Asset API.

    [NativeCall] public static partial IntPtr LoadObject(string Path);
    [NativeCall] public static partial IntPtr PinObject(IntPtr Object);
    [NativeCall] public static partial void UnpinObject(IntPtr Pin);
    [NativeCall] public static partial bool AssetExists(string Path);
    [NativeCall] public static partial void LoadObjectAsync(string Path, IntPtr Callback);

    /// <summary>A loaded object's asset path (registry reverse lookup), or "" if it has none.</summary>
    [NativeCall] public static partial string GetObjectPath(IntPtr Object);

    // Weak-handle validity backing NativeObject. ObjectGetHandle packs a live CObject*'s (Index, Generation)
    // as Generation<<32 | Index (Index = -1 if untracked); ObjectResolve returns the live pointer only if that
    // handle still names a live, non-destroyed object, else zero. Pure reads -> SuppressGCTransition.
    [NativeCall(SuppressGCTransition = true)] public static partial long ObjectGetHandle(IntPtr Object);
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr ObjectResolve(int Index, int Generation);
    [NativeCall(SuppressGCTransition = true)] public static partial IntPtr ObjectGetEntry(IntPtr Object);
    [NativeCall(SuppressGCTransition = true)] public static partial int ObjectLayoutOffset(int Which);

    // Per-CObject managed-instance cache backing Wrapper<T>.ForObject: Get returns the weak GC handle of the
    // wrapper this object already has (or zero), Set installs one and frees whatever it replaces (a zero
    // handle just clears). See Core/Object/ManagedInstance.h for the ownership rules.

    // No suppressed transition, since the table locks and Set frees a GC handle, re-entering the runtime.
    [NativeCall] public static partial IntPtr ObjectGetManagedInstance(IntPtr Object);
    [NativeCall] public static partial void ObjectSetManagedInstance(IntPtr Object, IntPtr Handle);
    [NativeCall] public static partial int ObjectAdoptScriptTwin(IntPtr Object, IntPtr WeakHandle);

    // Frees every cached managed instance. Called from the script teardown contract before the collectible ALC
    // unloads: Scriptable subclass instances are held by STRONG handles in that table and would pin it.
    [NativeCall] public static partial void ReleaseAllManagedInstances();

    // Cancels every timer holding a managed callback, whose delegates would otherwise root this generation.

    // Generic per-property-type accessors. The Reflector emits these for non-blittable properties
    // (FString/FName/object ref) with the property's FProperty* token (Prop) resolved once and cached;
    // C is the container (the live component/object handle). Blittable properties never reach here -- they
    // read/write native memory directly at the property's offset.

    // FName get = the generated two-pass buffer ABI (an interned id has to be resolved to text natively);
    // string set / object ref = generated string/pointer args. There is deliberately no PropGetString: an
    // FString is read in place off the property's offset via NativeMarshal.ReadString, with no crossing.

    [NativeCall] public static partial void PropSetString(IntPtr C, IntPtr Prop, string Value);
    [NativeCall] public static partial string PropGetName(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetName(IntPtr C, IntPtr Prop, string Value);
    [NativeCall] public static partial IntPtr PropGetObject(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetObject(IntPtr C, IntPtr Prop, IntPtr Object);

    // Asset reference: the virtual path, which is how C# stores one too (Lumina.FSoftObjectPath). Same
    // two-pass buffer ABI as PropGetName.
    [NativeCall] public static partial string PropGetAssetPath(IntPtr C, IntPtr Prop);
    [NativeCall] public static partial void PropSetAssetPath(IntPtr C, IntPtr Prop, string Path);

    // The element ops table for an array property, so a TVector<T> view can be built over any reflected
    // array -- including one appended to a minted script class, which has no generated per-property export.
    [NativeCall] public static partial IntPtr PropVectorOps(IntPtr Prop);
    [NativeCall] public static partial IntPtr PropMapOps(IntPtr Prop);

    // Assigns an FString at a raw address; the write half of a string container element (reads decode the
    // native string in place with no crossing). See ElementMarshal (EElementKind.String).
    [NativeCall] public static partial void StringAssign(IntPtr String, string Value);

    // Assigns a TStrongObjectPtr at a raw address, releasing the old reference and adding one to the new. The write
    // half of an object container element: a raw pointer store would skip the refcount. See ElementMarshal (EElementKind.ObjectRef).
    [NativeCall] public static partial void SetObjectPtr(IntPtr Slot, IntPtr Object);

    [NativeCall] public static partial IntPtr GetObjectPtr(IntPtr Slot);

    // FName interning. Address-based, not property-based, so the same pair serves a member and an element of
    // a TVector<FName>. FName itself is POD, so nothing else about it crosses -- reads and writes of the
    // value are plain in-place memory access, like any other blittable mirror.
    [NativeCall] public static partial void NameFromString(string Value, IntPtr OutName);
    [NativeCall] public static partial string NameToString(IntPtr Name);

    [NativeCall] public static partial ulong DelegateBind(IntPtr Delegate, IntPtr Thunk, IntPtr Context);

    [NativeCall(EntryPoint = "LuminaSharp_MessageBus_TypeKey")] public static partial ulong MessageBusTypeKey(string Name);
    [NativeCall(EntryPoint = "LuminaSharp_MessageBus_Subscribe")] public static partial ulong MessageBusSubscribe(ulong World, uint Channel, uint Owner, ulong Type, uint Match, IntPtr Thunk, IntPtr Context);
    [NativeCall(EntryPoint = "LuminaSharp_MessageBus_Unsubscribe")] public static partial uint MessageBusUnsubscribe(ulong World, ulong Id);
    [NativeCall(EntryPoint = "LuminaSharp_MessageBus_UnsubscribeAll")] public static partial void MessageBusUnsubscribeAll(ulong World, uint Owner);
    [NativeCall(EntryPoint = "LuminaSharp_MessageBus_Send")] public static partial void MessageBusSend(ulong World, uint Route, uint Entity, uint Channel, uint Kind, ulong Type, IntPtr Data, uint Size, IntPtr Struct, uint IncludeSelf);
    [NativeCall] public static partial void DelegateUnbind(IntPtr Delegate, ulong Handle);
    [NativeCall] public static partial int DelegateArgCount(IntPtr DelegateProperty);
    [NativeCall] public static partial IntPtr DelegateArgProperty(IntPtr DelegateProperty, int Index);
}
